name: TaskiAI
options:
  bundleIdPrefix: com.taskiai
  settings:
    base:
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
  createIntermediateGroups: true
targets:
  TaskiAI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TaskiAI/TaskiAI
      - path: assets
        type: folder
        buildPhase: resources
    dependencies: []
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskiai.app
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: TaskiAI/TaskiAI/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
  TaskiAITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TaskiAITests
    dependencies:
      - target: TaskiAI
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGNING_ALLOWED: NO
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
schemes:
  TaskiAI:
    build:
      targets:
        TaskiAI: all
    test:
      targets:
        - name: TaskiAITests
      gatherCoverageData: false
