name: TaskiAI
options:
  bundleIdPrefix: com.taskiai
targets:
  TaskiAI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TaskiAI/TaskiAI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taskiai.app
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: TaskiAI/TaskiAI/Info.plist
  TaskiAITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TaskiAITests
    dependencies:
      - target: TaskiAI
schemes: {}
