name: Generate Xcode Project

on:
  workflow_dispatch:
    inputs:
      commit-message:
        description: Commit message for generated Xcode project
        required: false
        default: 'chore: generate TaskiAI.xcodeproj via XcodeGen'

permissions:
  contents: write

jobs:
  generate:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest installed Xcode
        run: |
          set -euo pipefail
          XCODE_PATH=$(ls -d /Applications/Xcode_*.app | sort -V | tail -n1)
          sudo xcode-select -s "$XCODE_PATH"
          xcodebuild -version

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen@2.41 || brew install xcodegen

      - name: Generate Xcode project
        run: |
          rm -rf TaskiAI.xcodeproj
          xcodegen generate --spec Project.yml --project-root .
          test -d TaskiAI.xcodeproj

      - name: Commit and push if changed
        env:
          MSG: ${{ inputs.commit-message }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add TaskiAI.xcodeproj
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "$MSG"
            git push
          fi
