name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Install XcodeGen (pinned)
        run: |
          brew update
          brew install xcodegen@2.41 || brew install xcodegen

      - name: Verify repository paths
        run: |
          set -euo pipefail
          pwd
          ls -la
          ls -la TaskiAI
          ls -la TaskiAI/TaskiAI
          test -d TaskiAI/TaskiAI

      - name: Regenerate Xcode project for Xcode 15.4
        run: |
          rm -rf TaskiAI.xcodeproj
          xcodegen generate --spec Project.yml --project-root .

      - name: Cache SwiftPM artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved', 'Project.yml') }}

      - name: Show schemes
        run: |
          ls -la
          test -d TaskiAI.xcodeproj
          xcodebuild -list -project TaskiAI.xcodeproj

      - name: Build and test (iOS Simulator)
        env:
          NSUnbufferedIO: "YES"
        run: |
          set -euo pipefail
          xcodebuild \
            -project TaskiAI.xcodeproj \
            -scheme TaskiAI \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -sdk iphonesimulator \
            -configuration Debug \
            clean build test
        shell: bash
