name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest installed Xcode
        run: |
          set -euo pipefail
          echo "Available Xcodes:" && ls -1 /Applications | grep -E '^Xcode_.*\.app' || true
          XCODE_PATH=$(ls -d /Applications/Xcode_*.app | sort -V | tail -n1)
          echo "Selecting $XCODE_PATH"
          sudo xcode-select -s "$XCODE_PATH"
          xcodebuild -version

      - name: Install XcodeGen (pinned)
        run: |
          brew update
          brew install xcodegen@2.41 || brew install xcodegen

      - name: Verify repository paths
        run: |
          set -euo pipefail
          pwd
          ls -la
          ls -la TaskiAI
          ls -la TaskiAI/TaskiAI
          test -d TaskiAI/TaskiAI

      - name: Regenerate Xcode project for Xcode 15.4
        run: |
          rm -rf TaskiAI.xcodeproj
          xcodegen generate --spec Project.yml --project-root .

      - name: Cache SwiftPM artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved', 'Project.yml') }}

      - name: Show schemes
        run: |
          ls -la
          test -d TaskiAI.xcodeproj
          xcodebuild -list -project TaskiAI.xcodeproj

      - name: Resolve available iOS Simulator
        id: sim
        shell: bash
        run: |
          set -euo pipefail
          name=$(xcrun simctl list devices available | awk -F'\(' '/iPhone/ {print $1; exit}' | sed -e 's/^ *//;s/ *$//')
          if [ -z "$name" ]; then name="iPhone 15"; fi
          echo "Using simulator: $name"
          echo "device=$name" >> "$GITHUB_OUTPUT"

      - name: Resolve default scheme (JSON)
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          json=$(xcodebuild -list -project TaskiAI.xcodeproj -json | tr -d '\n')
          scheme=$(ruby -r json -e "j=JSON.parse(STDIN.read); puts((j['project'] && j['project']['schemes'] && j['project']['schemes'][0]) || (j['project'] && j['project']['targets'] && j['project']['targets'][0]) || 'TaskiAI')" <<< "$json")
          echo "Using scheme: $scheme"
          echo "scheme=$scheme" >> "$GITHUB_OUTPUT"

      - name: Build and test (iOS Simulator)
        env:
          NSUnbufferedIO: "YES"
        run: |
          set -euo pipefail
          xcodebuild \
            -project TaskiAI.xcodeproj \
            -scheme "${{ steps.resolve.outputs.scheme }}" \
            -destination "platform=iOS Simulator,name=${{ steps.sim.outputs.device }}" \
            -sdk iphonesimulator \
            -configuration Debug \
            clean build test
        shell: bash
